services:
  - type: web
    name: binary-top3-bot
    env: docker
    plan: free
    region: frankfurt
    dockerfilePath: ./Dockerfile
    envVars:
      - key: TELEGRAM_BOT_TOKEN
        sync: false
      - key: TWELVEDATA_API_KEY
        sync: false
      - key: AI_API_KEY
        sync: false
      - key: AI_MODEL
        value: llama-3.3-70b-versatile
